---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-audit-my-domain-v1alpha1-watch
  failurePolicy: Fail
  name: mwatch-v1alpha1.kb.io
  rules:
  - apiGroups:
    - audit.my.domain
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - watches
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-audit-my-domain-v1alpha1-watch
  failurePolicy: Fail
  name: vwatch-v1alpha1.kb.io
  rules:
  - apiGroups:
    - audit.my.domain
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - watches
  sideEffects: None
